name: "LandingZone"
# on:
#   workflow_dispatch:
on: 
  pull_request:
    types: [review_requested]

jobs:
  Plan_Dev:
    uses: vaibhavss/rapidoxengine/.github/workflows/core_plan_workflow.yml@main
    with:
      path: demo_flat_config                ## Path to terraform root module (Required)
      tf_version: latest                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      az_resource_group: remotestaterg    ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: azuretfremotestatestr    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: tfstate ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: dev-deploy             ## AZ backend - Specifies name that will be given to terraform state file and plan artifact (Required)
      tf_vars_file: values-dev.tfvars    ## Terraform TFVARS (Required)
      enable_TFSEC: true                 ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.DEV_ARM_SUB_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}             ## ARM Tenant ID
      

  Deploy_Dev:
    needs: Plan_Dev
    uses: vaibhavss/rapidoxengine/.github/workflows/core_apply_workflow.yml@main
    with:
      path: demo_flat_config                ## Path to terraform root module (Required)
      tf_version: latest                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      az_resource_group: remotestaterg   ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: azuretfremotestatestr    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: tfstate ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: dev-deploy             ## AZ backend - Specifies name of the terraform state file and workflow artifact to download (Required)
      gh_environment: dev        ## GH Environment. Default=null - (Optional)
    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.DEV_ARM_SUB_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}             ## ARM Tenant ID
      

  Plan_Hub:
    needs: Plan_Dev
    uses: vaibhavss/rapidoxengine/.github/workflows/core_plan_workflow.yml@main
    with:
      path: demo_flat_config                ## Path to terraform root module (Required)
      tf_version: latest                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      az_resource_group: RG-HUB-TFSTATESTORAGE    ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: rapidoxenginestatefiles    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: tfstates ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: hub-deploy             ## AZ backend - Specifies name that will be given to terraform state file and plan artifact (Required)
      tf_vars_file: values-hub.tfvars    ## Terraform TFVARS (Required)
      enable_TFSEC: true                 ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}             ## ARM Tenant ID
      

  Deploy_Hub:
    needs: Plan_Hub
    uses: vaibhavss/rapidoxengine/.github/workflows/core_apply_workflow.yml@main
    with:
      path: demo_flat_config                ## Path to terraform root module (Required)
      tf_version: latest                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      az_resource_group: RG-HUB-TFSTATESTORAGE    ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: rapidoxenginestatefiles    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: tfstates ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: hub-deploy             ## AZ backend - Specifies name of the terraform state file and workflow artifact to download (Required)
      gh_environment: hub        ## GH Environment. Default=null - (Optional)
    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.ARM_SUBSCRIPTION_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}             ## ARM Tenant ID
      

  Plan_Prd:
    needs: Plan_Dev
    uses: vaibhavss/rapidoxengine/.github/workflows/core_plan_workflow.yml@main
    with:
      path: demo_flat_config                ## Path to terraform root module (Required)
      tf_version: latest                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      az_resource_group: RG-PRD-TFSTATESTORAGE    ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: prdrapidoxenginestate    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: tfstate ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: prd-deploy             ## AZ backend - Specifies name that will be given to terraform state file and plan artifact (Required)
      tf_vars_file: values-hub.tfvars    ## Terraform TFVARS (Required)
      enable_TFSEC: true                 ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.PRD_ARM_SUB_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}             ## ARM Tenant ID
      

  Deploy_Prd:
    needs: Plan_prd
    uses: vaibhavss/rapidoxengine/.github/workflows/core_apply_workflow.yml@main
    with:
      path: demo_flat_config                ## Path to terraform root module (Required)
      tf_version: latest                 ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      az_resource_group: RG-PRD-TFSTATESTORAGE    ## AZ backend - AZURE Resource Group hosting terraform backend storage acc (Required)
      az_storage_acc: prdrapidoxenginestate    ## AZ backend - AZURE terraform backend storage acc (Required)
      az_container_name: tfstate ## AZ backend - AZURE storage container hosting state files (Required)
      tf_key: prd-deploy             ## AZ backend - Specifies name of the terraform state file and workflow artifact to download (Required)
      gh_environment: prd        ## GH Environment. Default=null - (Optional)
    secrets:
      arm_client_id: ${{ secrets.ARM_CLIENT_ID }}             ## ARM Client ID 
      arm_client_secret: ${{ secrets.ARM_CLIENT_SECRET }}     ## ARM Client Secret
      arm_subscription_id: ${{ secrets.PRD_ARM_SUB_ID }} ## ARM Subscription ID
      arm_tenant_id: ${{ secrets.ARM_TENANT_ID }}             ## ARM Tenant ID
      